# Generated by Django 5.2.17 on 2026-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True, verbose_name="key")),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sort order"),
                ),
            ],
            options={
                "verbose_name": "dashboard widget",
                "verbose_name_plural": "dashboard widgets",
                "ordering": ["sort_order", "key"],
                "permissions": [
                    ("view_dashboard", "Can view the KPI dashboard"),
                    ("export_statutoryreport", "Can export a statutory or custom report"),
                ],
            },
        ),
    ]
