# Generated by Django 5.2.17 on 2026-08-19 09:46

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed term"),
                            ("probation", "Probation"),
                            ("part_time", "Part time"),
                        ],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="position")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "basic_salary",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="basic salary"
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="registry.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract",
                "verbose_name_plural": "contracts",
                "ordering": ["-start_date"],
                "permissions": [("export_payroll", "Can export the payroll-ready contract list")],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("sick", "Sick"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("study", "Study"),
                            ("unpaid", "Unpaid"),
                        ],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("endorsed", "Endorsed by supervisor"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("endorsed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, verbose_name="decision notes")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endorsed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="registry.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "leave request",
                "verbose_name_plural": "leave requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_leaverequest", "Can give the final decision on a leave request")
                ],
            },
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1 (unsatisfactory) to 5 (outstanding).", verbose_name="rating"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
                (
                    "promotion_recommended",
                    models.BooleanField(default=False, verbose_name="promotion recommended"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals",
                        to="registry.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "appraisal",
                "verbose_name_plural": "appraisals",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "academic_year"), name="one_appraisal_per_staff_per_year"
                    )
                ],
            },
        ),
    ]
