# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="code")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "credit_hours",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="credit hours",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Year of study this course is normally taken in.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="level",
                    ),
                ),
                ("contact_hours_per_week", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("code", models.CharField(max_length=10, unique=True, verbose_name="code")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["faculty__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in student IDs, e.g. ENG.",
                        max_length=10,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "faculty",
                "verbose_name_plural": "faculties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "minimum_grade_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty to accept any pass.",
                        max_digits=4,
                        null=True,
                        verbose_name="minimum grade point",
                    ),
                ),
                (
                    "is_concurrent_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="Allow registering for both in the same semester.",
                        verbose_name="may be taken concurrently",
                    ),
                ),
            ],
            options={
                "verbose_name": "prerequisite",
                "verbose_name_plural": "prerequisites",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "code",
                    models.CharField(
                        help_text="Used in student IDs, e.g. CIV.",
                        max_length=15,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor's Degree"),
                            ("postgraduate_diploma", "Postgraduate Diploma"),
                            ("masters", "Master's Degree"),
                            ("phd", "Doctorate"),
                        ],
                        max_length=25,
                        verbose_name="award",
                    ),
                ),
                (
                    "duration_years",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="duration (years)",
                    ),
                ),
                (
                    "total_credits_required",
                    models.PositiveSmallIntegerField(
                        default=120, verbose_name="credits required to graduate"
                    ),
                ),
                (
                    "min_credits_per_semester",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="minimum credits per semester"
                    ),
                ),
                (
                    "max_credits_per_semester",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Registration ceiling enforced at course registration (FR-ENR-02).",
                        verbose_name="maximum credits per semester",
                    ),
                ),
                (
                    "entry_requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Configurable rules screened against applicants in Phase 2 (FR-ADM-03), e.g. {"min_certificate_grade": "C", "required_subjects": ["Mathematics"]}.',
                        verbose_name="entry requirements",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off to stop admissions without affecting enrolled students.",
                        verbose_name="accepting students",
                    ),
                ),
            ],
            options={
                "verbose_name": "programme",
                "verbose_name_plural": "programmes",
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "version",
                    models.CharField(
                        help_text="e.g. 2026-v1", max_length=20, verbose_name="version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")],
                        default="draft",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_curricula",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "effective_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curricula_started",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "effective_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty while this is the version in force.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curricula_ended",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum version",
                "verbose_name_plural": "curriculum versions",
                "ordering": ["programme__name", "-effective_from__start_date"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(default=1, verbose_name="year of study"),
                ),
                (
                    "semester_sequence",
                    models.PositiveSmallIntegerField(default=1, verbose_name="semester"),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=True,
                        help_text="Core courses are compulsory; others are electives.",
                        verbose_name="core",
                    ),
                ),
                (
                    "elective_group",
                    models.CharField(
                        blank=True,
                        help_text='For "choose 2 of 4" sets — give the alternatives the same group name.',
                        max_length=50,
                        verbose_name="elective group",
                    ),
                ),
                (
                    "min_group_choices",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="choices required from group"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curricula",
                        to="curriculum.course",
                    ),
                ),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="curriculum.curriculumversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum course",
                "verbose_name_plural": "curriculum courses",
                "ordering": ["year_of_study", "semester_sequence", "course__code"],
            },
        ),
    ]
