# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                help_text="Defines the scope of the Head of Department role.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headships",
                to="registry.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                help_text="The department that owns and teaches this course.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="curriculum.department",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="dean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deanships",
                to="registry.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculties",
                to="academics.institution",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="curriculum.faculty",
            ),
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prerequisites",
                to="curriculum.course",
            ),
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="required_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for",
                to="curriculum.course",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programmes",
                to="curriculum.department",
            ),
        ),
        migrations.AddField(
            model_name="curriculumversion",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculum_versions",
                to="curriculum.programme",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumcourse",
            constraint=models.UniqueConstraint(
                fields=("curriculum_version", "course"), name="unique_course_per_curriculum"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["department", "level"], name="curriculum__departm_836635_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prerequisite",
            constraint=models.UniqueConstraint(
                fields=("course", "required_course"), name="unique_prerequisite_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="prerequisite",
            constraint=models.CheckConstraint(
                condition=models.Q(("course", models.F("required_course")), _negated=True),
                name="prerequisite_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumversion",
            constraint=models.UniqueConstraint(
                fields=("programme", "version"), name="unique_curriculum_version_per_programme"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("programme",),
                name="one_active_curriculum_per_programme",
            ),
        ),
    ]
