# Generated by Django 5.2.17 on 2026-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="admission_quota_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Merit list seat allocation (FR-ADM-06), e.g. {"total_seats": 50, "reserved": [{"category": "state", "value": "warrap", "seats": 5}]}. Empty means no cap — every applicant ranks and none is excluded.',
                verbose_name="admission quota rules",
            ),
        ),
    ]
