# Generated by Django 5.2.17 on 2026-08-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollment", "0001_initial"),
        ("timetabling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_waiver",
                        to="enrollment.courseregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance waiver",
                "verbose_name_plural": "attendance waivers",
                "permissions": [
                    (
                        "override_block",
                        "Can authorise a registration to sit an exam despite a low attendance percentage",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("session_date", models.DateField(verbose_name="session date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="notes")),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_records",
                        to="enrollment.courseregistration",
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_records",
                        to="timetabling.timetableentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "session record",
                "verbose_name_plural": "session records",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["registration", "session_date"],
                        name="attendance__registr_cb690b_idx",
                    ),
                    models.Index(
                        fields=["timetable_entry", "session_date"],
                        name="attendance__timetab_60bc71_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timetable_entry", "session_date", "registration"),
                        name="one_record_per_student_per_session",
                    )
                ],
            },
        ),
    ]
