# Generated by Django 5.2.17 on 2026-08-19 10:15

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostelPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "termly_fee",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="termly fee",
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "hostel policy",
                "verbose_name_plural": "hostel policy",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("building", models.CharField(max_length=100, verbose_name="building")),
                ("room_number", models.CharField(max_length=20, verbose_name="room number")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacity",
                    ),
                ),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=15,
                        verbose_name="restricted to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ["building", "room_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "room_number"), name="one_room_per_building_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("vacated", "Vacated")],
                        default="active",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("allocated_at", models.DateTimeField(verbose_name="allocated at")),
                (
                    "vacated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="vacated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostel_allocations",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostel_allocations",
                        to="registry.student",
                    ),
                ),
                (
                    "vacated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="hostel.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation",
                "verbose_name_plural": "allocations",
                "ordering": ["-allocated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("student",),
                        name="one_active_allocation_per_student",
                    )
                ],
            },
        ),
    ]
