# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=120, unique=True, verbose_name="scope")),
                ("last_value", models.PositiveIntegerField(default=0, verbose_name="last value")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "ID sequence",
                "verbose_name_plural": "ID sequences",
                "ordering": ["scope"],
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_op_id", models.UUIDField(unique=True, verbose_name="client operation id")),
                ("entity", models.CharField(max_length=100, verbose_name="entity")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "client_timestamp",
                    models.DateTimeField(blank=True, null=True, verbose_name="client timestamp"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="received at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate (already applied)"),
                            ("conflict", "Conflict — held for review"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="result")),
                ("error_detail", models.TextField(blank=True, verbose_name="error detail")),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=100, verbose_name="device id"),
                ),
                ("target_object_id", models.CharField(blank=True, max_length=64)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync operation",
                "verbose_name_plural": "sync operations",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity", models.CharField(max_length=100, verbose_name="entity")),
                ("target_object_id", models.CharField(blank=True, max_length=64)),
                ("field_name", models.CharField(blank=True, max_length=100, verbose_name="field")),
                ("server_value", models.TextField(blank=True, verbose_name="server value")),
                ("client_value", models.TextField(blank=True, verbose_name="client value")),
                ("server_updated_at", models.DateTimeField(blank=True, null=True)),
                ("client_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved_server", "Resolved — kept server value"),
                            ("resolved_client", "Resolved — accepted client value"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_reason",
                    models.TextField(blank=True, verbose_name="resolution reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_sync_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sync_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="core.syncoperation",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync conflict",
                "verbose_name_plural": "sync conflicts",
                "ordering": ["-created_at"],
                "permissions": [("resolve_syncconflict", "Can resolve sync conflicts")],
            },
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(fields=["entity", "status"], name="core_syncop_entity_73092d_idx"),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(
                fields=["submitted_by", "-received_at"], name="core_syncop_submitt_1fd5ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(
                fields=["device_id", "-received_at"], name="core_syncop_device__db6e57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["status", "-created_at"], name="core_syncco_status_ffce1f_idx"
            ),
        ),
    ]
