"""Request-scoped middleware: correlation id and audit actor."""

from __future__ import annotations

from collections.abc import Callable

from django.http import HttpRequest, HttpResponse

from apps.core import context

REQUEST_ID_HEADER = "X-Request-ID"


class RequestIDMiddleware:
    """Attach a correlation id to every request.

    Honours an inbound `X-Request-ID` so a value generated by the PWA (including
    one attached to a write that was queued offline hours earlier) survives into
    the server logs and the audit trail.
    """

    def __init__(self, get_response: Callable[[HttpRequest], HttpResponse]) -> None:
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        inbound = request.headers.get(REQUEST_ID_HEADER, "").strip()
        request_id = inbound[:64] if inbound else context.new_request_id()

        context.set_request_id(request_id)
        request.request_id = request_id  # type: ignore[attr-defined]

        try:
            response = self.get_response(request)
            response[REQUEST_ID_HEADER] = request_id
            return response
        finally:
            # Threads are pooled and reused, so a leaked id would mislabel the
            # next request's audit entries.
            context.clear()


class AuditActorMiddleware:
    """Make the acting user discoverable from anywhere in the call stack.

    Stores the *request*, not the user. With JWT the user is resolved by DRF
    inside the view, well after middleware has run, so reading `request.user`
    here would record every API write as anonymous.
    """

    def __init__(self, get_response: Callable[[HttpRequest], HttpResponse]) -> None:
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        context.set_request(request)
        try:
            return self.get_response(request)
        finally:
            context.clear()
