# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, max_length=64, verbose_name="object id"),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="Label captured at write time, so the entry stays readable.",
                        max_length=255,
                        verbose_name="object",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Signed in"),
                            ("logout", "Signed out"),
                            ("login_failed", "Failed sign-in"),
                            ("view_sensitive", "Viewed sensitive record"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("role_grant", "Role granted"),
                            ("role_revoke", "Role revoked"),
                            ("sync_overwrite", "Overwritten by offline sync"),
                            ("export", "Exported data"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100, verbose_name="field")),
                ("old_value", models.TextField(blank=True, null=True, verbose_name="old value")),
                ("new_value", models.TextField(blank=True, null=True, verbose_name="new value")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="description"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                ("actor_name", models.CharField(blank=True, max_length=150, verbose_name="actor")),
                (
                    "actor_role",
                    models.CharField(blank=True, max_length=100, verbose_name="actor role"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="request id"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="recorded at",
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("row_hash", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit entry",
                "verbose_name_plural": "audit trail",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="audit_audit_content_895b94_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="audit_audit_actor_i_1175ab_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"
                    ),
                ],
            },
        ),
    ]
