# Generated by Django 5.2.17 on 2026-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("login", "Signed in"),
                    ("logout", "Signed out"),
                    ("login_failed", "Failed sign-in"),
                    ("view_sensitive", "Viewed sensitive record"),
                    ("approve", "Approved"),
                    ("reject", "Rejected"),
                    ("role_grant", "Role granted"),
                    ("role_revoke", "Role revoked"),
                    ("sync_overwrite", "Overwritten by offline sync"),
                    ("export", "Exported data"),
                    ("mfa_enabled", "MFA enabled"),
                    ("mfa_disabled", "MFA disabled"),
                ],
                max_length=20,
                verbose_name="action",
            ),
        ),
    ]
