# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("company", "Company"),
                            ("individual", "Individual"),
                            ("scholarship_fund", "Scholarship fund"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, verbose_name="contact person"),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "sponsor",
                "verbose_name_plural": "sponsors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Generated from the institution's template. Never reused (FR-REG-01).",
                        max_length=50,
                        unique=True,
                        verbose_name="student ID",
                    ),
                ),
                (
                    "current_level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="year of study",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deferred", "Deferred"),
                            ("withdrawn", "Withdrawn"),
                            ("graduated", "Graduated"),
                            ("expelled", "Expelled"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("self", "Self-sponsored"),
                            ("government", "Government-sponsored"),
                            ("scholarship", "Scholarship"),
                            ("bursary", "Bursary"),
                            ("employer", "Employer-sponsored"),
                            ("ngo", "NGO-sponsored"),
                        ],
                        default="self",
                        max_length=15,
                        verbose_name="sponsorship",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="first name")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, verbose_name="middle name"),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="last name")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=15,
                        verbose_name="gender",
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(blank=True, max_length=50, verbose_name="national ID number"),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, verbose_name="passport number"),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="South Sudanese", max_length=100, verbose_name="nationality"
                    ),
                ),
                (
                    "state_of_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("central_equatoria", "Central Equatoria"),
                            ("eastern_equatoria", "Eastern Equatoria"),
                            ("western_equatoria", "Western Equatoria"),
                            ("jonglei", "Jonglei"),
                            ("unity", "Unity"),
                            ("upper_nile", "Upper Nile"),
                            ("warrap", "Warrap"),
                            ("northern_bahr_el_ghazal", "Northern Bahr el Ghazal"),
                            ("western_bahr_el_ghazal", "Western Bahr el Ghazal"),
                            ("lakes", "Lakes"),
                            ("abyei", "Abyei Administrative Area"),
                            ("greater_pibor", "Greater Pibor Administrative Area"),
                            ("ruweng", "Ruweng Administrative Area"),
                            ("outside", "Outside South Sudan"),
                        ],
                        help_text="Required for statutory returns (FR-RPT-03).",
                        max_length=30,
                        verbose_name="state of origin",
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100, verbose_name="county")),
                (
                    "has_disability",
                    models.BooleanField(default=False, verbose_name="has a disability"),
                ),
                (
                    "disability_details",
                    models.TextField(
                        blank=True,
                        help_text="Supports special-needs provision and quota rules.",
                        verbose_name="disability details",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="alternate phone"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("physical_address", models.TextField(blank=True, verbose_name="address")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/", verbose_name="photo"
                    ),
                ),
                (
                    "previous_institution",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous institution"
                    ),
                ),
                (
                    "previous_qualification",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous qualification"
                    ),
                ),
                (
                    "transfer_credits",
                    models.PositiveSmallIntegerField(default=0, verbose_name="transfer credits"),
                ),
                (
                    "admitted_on",
                    models.DateField(blank=True, null=True, verbose_name="admitted on"),
                ),
                (
                    "graduated_on",
                    models.DateField(blank=True, null=True, verbose_name="graduated on"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active record")),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The syllabus this student is assessed against (FR-CUR-03).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="curriculum.curriculumversion",
                    ),
                ),
                (
                    "entry_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entering_students",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="curriculum.programme",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="registry.sponsor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Portal login. Empty until the account is activated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ["last_name", "first_name"],
                "permissions": [("change_student_status", "Can change a student's status")],
            },
        ),
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("full_name", models.CharField(max_length=150, verbose_name="full name")),
                ("relationship", models.CharField(max_length=50, verbose_name="relationship")),
                ("phone", models.CharField(max_length=32, verbose_name="phone")),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="alternate phone"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("is_primary", models.BooleanField(default=False, verbose_name="primary contact")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "next of kin",
                "verbose_name_plural": "next of kin",
                "ordering": ["-is_primary", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("transcript", "Transcript"),
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("photo", "Passport photo"),
                            ("medical_clearance", "Medical clearance"),
                            ("recommendation", "Recommendation letter"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "file",
                    models.FileField(upload_to="students/documents/%Y/%m/", verbose_name="file"),
                ),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="size (bytes)")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="SHA-256"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="registry.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_student_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_student_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student document",
                "verbose_name_plural": "student documents",
                "ordering": ["-created_at"],
                "permissions": [
                    ("verify_studentdocument", "Can verify uploaded student documents")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deferred", "Deferred"),
                            ("withdrawn", "Withdrawn"),
                            ("graduated", "Graduated"),
                            ("expelled", "Expelled"),
                        ],
                        max_length=15,
                        verbose_name="from",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deferred", "Deferred"),
                            ("withdrawn", "Withdrawn"),
                            ("graduated", "Graduated"),
                            ("expelled", "Expelled"),
                        ],
                        max_length=15,
                        verbose_name="to",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Required — a status change without a stated reason is not defensible.",
                        verbose_name="reason",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Minute number or letter reference authorising the change.",
                        max_length=100,
                        verbose_name="reference",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "status change",
                "verbose_name_plural": "status history",
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "staff_number",
                    models.CharField(max_length=50, unique=True, verbose_name="staff number"),
                ),
                (
                    "staff_category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("administrative", "Administrative"),
                            ("support", "Support"),
                        ],
                        default="academic",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("visiting", "Visiting"),
                            ("adjunct", "Adjunct"),
                        ],
                        default="full_time",
                        max_length=15,
                        verbose_name="appointment",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("senior_lecturer", "Senior Lecturer"),
                            ("lecturer", "Lecturer"),
                            ("assistant_lecturer", "Assistant Lecturer"),
                            ("teaching_assistant", "Teaching Assistant"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="lecturer",
                        max_length=25,
                        verbose_name="rank",
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="highest qualification"
                    ),
                ),
                (
                    "date_of_hire",
                    models.DateField(blank=True, null=True, verbose_name="date of hire"),
                ),
                (
                    "contract_end_date",
                    models.DateField(blank=True, null=True, verbose_name="contract ends"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=15,
                        verbose_name="gender",
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(blank=True, max_length=50, verbose_name="national ID number"),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                ("is_active", models.BooleanField(default=True, verbose_name="in service")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="curriculum.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "staff member",
                "verbose_name_plural": "staff",
                "ordering": ["user__last_name", "user__first_name"],
                "indexes": [
                    models.Index(
                        fields=["department", "is_active"], name="registry_st_departm_3610e0_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["programme", "status"], name="registry_st_program_c3a48f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["entry_academic_year", "status"], name="registry_st_entry_a_61ad09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"], name="registry_st_last_na_f08eda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["national_id_number"], name="registry_st_nationa_8cd97f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["status", "current_level"], name="registry_st_status_85d81d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nextofkin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("student",),
                name="one_primary_next_of_kin_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["student", "document_type"], name="registry_st_student_8d02da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentstatushistory",
            index=models.Index(
                fields=["student", "-effective_date"], name="registry_st_student_e876c7_idx"
            ),
        ),
    ]
