# Generated by Django 5.2.17 on 2026-08-18 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0003_programme_admission_quota_rules"),
        ("enrollment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "weight_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="weight %",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=6,
                        verbose_name="maximum score",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1, verbose_name="sequence")),
                (
                    "grade_entry_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="grade entry deadline"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment",
                "verbose_name_plural": "assessments",
                "ordering": ["course", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="GradeAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("upheld", "Upheld"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("decision_notes", models.TextField(blank=True, verbose_name="decision notes")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appeals",
                        to="examinations.assessment",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_appeals",
                        to="enrollment.courseregistration",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "grade appeal",
                "verbose_name_plural": "grade appeals",
                "ordering": ["-created_at"],
                "permissions": [("decide_gradeappeal", "Can decide a grade appeal")],
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "score",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="score"),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically against the assessment's grade entry deadline (FR-EXM-02).",
                        verbose_name="entered late",
                    ),
                ),
                (
                    "moderated_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="moderated score",
                    ),
                ),
                ("moderation_notes", models.TextField(blank=True, verbose_name="moderation notes")),
                (
                    "is_irregular",
                    models.BooleanField(
                        default=False,
                        help_text="Exam malpractice or another irregularity (FR-EXM-08). Excludes this mark from a course result until cleared.",
                        verbose_name="flagged irregular",
                    ),
                ),
                (
                    "irregularity_notes",
                    models.TextField(blank=True, verbose_name="irregularity notes"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks",
                        to="examinations.assessment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks",
                        to="enrollment.courseregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "mark",
                "verbose_name_plural": "marks",
                "ordering": ["-created_at"],
                "permissions": [
                    ("moderate_result", "Can moderate (second-mark) a mark"),
                    ("flag_irregularity", "Can flag or clear an exam irregularity on a mark"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True, verbose_name="approval notes")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_approvals",
                        to="curriculum.programme",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_approvals",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "result approval",
                "verbose_name_plural": "result approvals",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_result", "Can approve a semester's results for publication (Senate)"),
                    ("publish_result", "Can publish approved results to students"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="one_assessment_name_per_course"
            ),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["registration"], name="examination_registr_195236_idx"),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["assessment"], name="examination_assessm_58e9e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.UniqueConstraint(
                fields=("registration", "assessment"),
                name="one_mark_per_registration_per_assessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("programme__isnull", False)),
                fields=("semester", "programme"),
                name="one_approval_per_semester_per_programme",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("programme__isnull", True)),
                fields=("semester",),
                name="one_all_programme_approval_per_semester",
            ),
        ),
    ]
