# Generated by Django 5.2.17 on 2026-08-19 09:09

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0003_programme_admission_quota_rules"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="year of study",
                    ),
                ),
                (
                    "residency",
                    models.CharField(
                        choices=[
                            ("local", "Local (South Sudanese)"),
                            ("international", "International"),
                        ],
                        max_length=15,
                        verbose_name="residency",
                    ),
                ),
                (
                    "amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="amount per semester"
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_structures",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_structures",
                        to="curriculum.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "fee structure",
                "verbose_name_plural": "fee structures",
                "ordering": ["academic_year", "programme", "level"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "invoice_number",
                    models.CharField(max_length=40, unique=True, verbose_name="invoice number"),
                ),
                (
                    "amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="amount"
                    ),
                ),
                (
                    "discount_amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="discount",
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("written_off", "Written off"),
                        ],
                        default="issued",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "fee_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="finance.feestructure",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "ordering": ["-created_at"],
                "permissions": [("view_defaulterreport", "Can view the fee-defaulter report")],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile money"),
                            ("bank_slip", "Bank slip"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=15,
                        verbose_name="method",
                    ),
                ),
                (
                    "amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=50, verbose_name="provider")),
                (
                    "reference",
                    models.CharField(max_length=120, unique=True, verbose_name="reference"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="receipt number",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="requested",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("decision_notes", models.TextField(blank=True, verbose_name="decision notes")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="finance.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ["-created_at"],
                "permissions": [("approve_refund", "Can approve or reject a refund request")],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of fees"),
                            ("fixed_amount", "Fixed amount"),
                        ],
                        max_length=15,
                        verbose_name="coverage",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="coverage %",
                    ),
                ),
                (
                    "fixed_amount",
                    apps.core.fields.MoneyAmountField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="fixed amount",
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Left blank for an institution-funded bursary.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="registry.sponsor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "scholarship",
                "verbose_name_plural": "scholarships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="feestructure",
            constraint=models.UniqueConstraint(
                fields=("programme", "academic_year", "level", "residency"),
                name="one_fee_structure_per_programme_year_level_residency",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["student", "status"], name="finance_inv_student_96f21e_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["semester", "status"], name="finance_inv_semeste_e83244_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("student", "semester"), name="one_invoice_per_student_per_semester"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["invoice", "status"], name="finance_pay_invoice_80fc36_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["method", "status"], name="finance_pay_method_de37b5_idx"),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.UniqueConstraint(
                fields=("student", "academic_year"), name="one_scholarship_per_student_per_year"
            ),
        ),
    ]
