# Generated by Django 5.2.17 on 2026-08-17 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=50, verbose_name="short name"),
                ),
                (
                    "mohest_code",
                    models.CharField(
                        blank=True,
                        help_text="Identifier used on statutory returns to the Ministry.",
                        max_length=50,
                        verbose_name="MoHEST code",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                        verbose_name="base currency",
                    ),
                ),
                (
                    "secondary_currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="USD",
                        help_text="Used for fee categories quoted in foreign currency.",
                        max_length=3,
                        verbose_name="secondary currency",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="institution/", verbose_name="logo"
                    ),
                ),
                (
                    "letterhead",
                    models.FileField(
                        blank=True, null=True, upload_to="institution/", verbose_name="letterhead"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "student_id_template",
                    models.CharField(
                        default="{faculty}/{programme}/{year}/{seq:04d}",
                        help_text="Placeholders: {faculty}, {programme}, {year}, {seq}. Example: ENG/CIV/2026/0042. Changing this does not renumber existing students.",
                        max_length=100,
                        verbose_name="student ID format",
                    ),
                ),
                (
                    "staff_id_template",
                    models.CharField(
                        default="STF/{year}/{seq:04d}",
                        max_length=100,
                        verbose_name="staff ID format",
                    ),
                ),
                (
                    "attendance_threshold_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        help_text="Below this, a student may be barred from examinations (FR-ATT-02).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="minimum attendance %",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="Africa/Juba", max_length=64, verbose_name="timezone"),
                ),
            ],
            options={
                "verbose_name": "institution",
                "verbose_name_plural": "institution",
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2026/2027", max_length=20, unique=True, verbose_name="name"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="starts")),
                ("end_date", models.DateField(verbose_name="ends")),
                ("is_current", models.BooleanField(default=False, verbose_name="current")),
            ],
            options={
                "verbose_name": "academic year",
                "verbose_name_plural": "academic years",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="only_one_current_academic_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "max_grade_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.00"),
                        help_text="4.00 or 5.00 depending on institutional policy.",
                        max_digits=4,
                        verbose_name="maximum grade point",
                    ),
                ),
                (
                    "pass_grade_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=4,
                        verbose_name="minimum passing grade point",
                    ),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="default scale")),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Set once results have been published against this scale. A locked scale cannot be edited, because changing a boundary would silently rewrite grades already on transcripts.",
                        verbose_name="locked",
                    ),
                ),
                (
                    "effective_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cohorts before this year keep their own scale.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grading_scales",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading scale",
                "verbose_name_plural": "grading scales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("letter", models.CharField(max_length=5, verbose_name="letter")),
                (
                    "min_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="from %",
                    ),
                ),
                (
                    "max_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="to %",
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, max_digits=4, verbose_name="grade point"),
                ),
                ("is_pass", models.BooleanField(default=True, verbose_name="counts as a pass")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Distinction, Pass, Fail",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="academics.gradingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "grade band",
                "verbose_name_plural": "grade bands",
                "ordering": ["scale", "-min_percent"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("sequence", models.PositiveSmallIntegerField(default=1, verbose_name="sequence")),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Semester 1", max_length=50, verbose_name="name"
                    ),
                ),
                ("teaching_start", models.DateField(verbose_name="teaching starts")),
                ("teaching_end", models.DateField(verbose_name="teaching ends")),
                (
                    "exam_start",
                    models.DateField(blank=True, null=True, verbose_name="examinations start"),
                ),
                (
                    "exam_end",
                    models.DateField(blank=True, null=True, verbose_name="examinations end"),
                ),
                (
                    "registration_opens",
                    models.DateTimeField(blank=True, null=True, verbose_name="registration opens"),
                ),
                (
                    "registration_closes",
                    models.DateTimeField(blank=True, null=True, verbose_name="registration closes"),
                ),
                (
                    "add_drop_closes",
                    models.DateTimeField(blank=True, null=True, verbose_name="add/drop closes"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="current")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "semester",
                "verbose_name_plural": "semesters",
                "ordering": ["-academic_year__start_date", "sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="gradingscale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="only_one_default_grading_scale",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.UniqueConstraint(
                fields=("scale", "letter"), name="unique_letter_per_scale"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "sequence"), name="unique_semester_sequence_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="only_one_current_semester",
            ),
        ),
    ]
