# Generated by Django 5.2.17 on 2026-08-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("event_date", models.DateField(verbose_name="date")),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="location")),
            ],
            options={
                "verbose_name": "alumni event",
                "verbose_name_plural": "alumni events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                (
                    "current_employer",
                    models.CharField(blank=True, max_length=200, verbose_name="current employer"),
                ),
                (
                    "current_position",
                    models.CharField(blank=True, max_length=200, verbose_name="current position"),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-employed"),
                            ("further_study", "In further study"),
                            ("unemployed", "Unemployed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=15,
                        verbose_name="employment status",
                    ),
                ),
                (
                    "is_contactable",
                    models.BooleanField(
                        default=True,
                        help_text="Off once a tracer contact bounces or they opt out.",
                        verbose_name="contactable",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumni_profile",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "alumni profile",
                "verbose_name_plural": "alumni profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
