# Generated by Django 5.2.17 on 2026-08-19 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("rejected", "Rejected"),
                            ("issued", "Issued"),
                        ],
                        default="requested",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("decision_notes", models.TextField(blank=True, verbose_name="decision notes")),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="decided at"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcript_requests",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "transcript request",
                "verbose_name_plural": "transcript requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssuedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "document_type",
                    models.CharField(
                        choices=[("transcript", "Transcript"), ("certificate", "Certificate")],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=40, unique=True, verbose_name="serial number"),
                ),
                ("issued_at", models.DateTimeField(verbose_name="issued at")),
                ("is_revoked", models.BooleanField(default=False, verbose_name="revoked")),
                ("revoked_reason", models.TextField(blank=True, verbose_name="revocation reason")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="revoked at"),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True,
                        help_text="Set only when issued despite an open graduation-clearance hold.",
                        verbose_name="clearance override reason",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="registry.student",
                    ),
                ),
                (
                    "transcript_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="documents.transcriptrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "issued document",
                "verbose_name_plural": "issued documents",
                "ordering": ["-issued_at"],
                "permissions": [
                    ("issue_certificate", "Can issue a certificate"),
                    ("revoke_document", "Can revoke an issued document"),
                    (
                        "override_clearance",
                        "Can issue a certificate despite an open clearance hold",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["student", "document_type"], name="documents_i_student_e69c54_idx"
                    )
                ],
            },
        ),
    ]
