# Generated by Django 5.2.17 on 2026-08-19 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0003_programme_admission_quota_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all_students", "All students"),
                            ("programme", 'A specific programme ("class")'),
                            ("alumni", "Alumni"),
                        ],
                        max_length=15,
                        verbose_name="audience",
                    ),
                ),
                ("sent_at", models.DateTimeField(verbose_name="sent at")),
                (
                    "recipient_count",
                    models.PositiveIntegerField(default=0, verbose_name="recipients"),
                ),
                ("sms_sent_count", models.PositiveIntegerField(default=0, verbose_name="SMS sent")),
                (
                    "email_sent_count",
                    models.PositiveIntegerField(default=0, verbose_name="emails sent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="curriculum.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
                "ordering": ["-sent_at"],
                "permissions": [
                    ("send_announcement", 'Can send an announcement to a programme ("class")'),
                    ("broadcast_all", "Can send an announcement to every student institution-wide"),
                ],
            },
        ),
    ]
