# Generated by Django 5.2.17 on 2026-08-18 15:40

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0003_programme_admission_quota_rules"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Generated on creation. Given to the applicant to track status.",
                        max_length=30,
                        unique=True,
                        verbose_name="reference number",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="first name")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, verbose_name="middle name"),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="last name")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=15,
                        verbose_name="gender",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="South Sudanese", max_length=100, verbose_name="nationality"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                (
                    "national_id_number",
                    models.CharField(blank=True, max_length=50, verbose_name="national ID number"),
                ),
                (
                    "state_of_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("central_equatoria", "Central Equatoria"),
                            ("eastern_equatoria", "Eastern Equatoria"),
                            ("western_equatoria", "Western Equatoria"),
                            ("jonglei", "Jonglei"),
                            ("unity", "Unity"),
                            ("upper_nile", "Upper Nile"),
                            ("warrap", "Warrap"),
                            ("northern_bahr_el_ghazal", "Northern Bahr el Ghazal"),
                            ("western_bahr_el_ghazal", "Western Bahr el Ghazal"),
                            ("lakes", "Lakes"),
                            ("abyei", "Abyei Administrative Area"),
                            ("greater_pibor", "Greater Pibor Administrative Area"),
                            ("ruweng", "Ruweng Administrative Area"),
                            ("outside", "Outside South Sudan"),
                        ],
                        max_length=30,
                        verbose_name="state of origin",
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100, verbose_name="county")),
                (
                    "has_disability",
                    models.BooleanField(default=False, verbose_name="has a disability"),
                ),
                (
                    "disability_details",
                    models.TextField(blank=True, verbose_name="disability details"),
                ),
                ("physical_address", models.TextField(blank=True, verbose_name="address")),
                (
                    "previous_institution",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous institution"
                    ),
                ),
                (
                    "previous_qualification",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous qualification"
                    ),
                ),
                (
                    "previous_grade",
                    models.CharField(
                        blank=True,
                        help_text="Screened against the programme's entry requirements (FR-ADM-03).",
                        max_length=10,
                        verbose_name="previous certificate grade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("offered", "Offer made"),
                            ("accepted", "Offer accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("enrolled", "Converted to student record"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("self_service", "Applicant portal"),
                            ("staff_entry", "Entered by staff (FR-ADM-02)"),
                        ],
                        default="self_service",
                        max_length=15,
                        verbose_name="source",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average of reviewer scores (FR-ADM-05).",
                        max_digits=6,
                        null=True,
                        verbose_name="score",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, verbose_name="decision reason")),
                (
                    "fee_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Must be true before the application can be submitted (FR-ADM-04).",
                        verbose_name="application fee paid",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who typed this in, for staff-entry applications.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intended_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="curriculum.programme",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="registry.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "application",
                "verbose_name_plural": "applications",
                "ordering": ["-created_at"],
                "permissions": [("decide_application", "Can accept or reject an application")],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("photo", "Passport photo"),
                            ("recommendation", "Recommendation letter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "file",
                    models.FileField(upload_to="admissions/documents/%Y/%m/", verbose_name="file"),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admissions.application",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_application_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "application document",
                "verbose_name_plural": "application documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "amount",
                    apps.core.fields.MoneyAmountField(
                        decimal_places=2, max_digits=16, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.CurrencyField(
                        choices=[
                            ("SSP", "South Sudanese Pound"),
                            ("USD", "US Dollar"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="SSP",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Units of the institution's base currency per unit of this currency.",
                        max_digits=18,
                        null=True,
                        verbose_name="exchange rate to base currency",
                    ),
                ),
                (
                    "fx_rate_date",
                    models.DateField(blank=True, null=True, verbose_name="exchange rate date"),
                ),
                ("provider", models.CharField(max_length=50)),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "application fee payment",
                "verbose_name_plural": "application fee payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "score",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="score"),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Configurable per-criterion breakdown, e.g. {"academic": 8, "interview": 7}.',
                        verbose_name="criteria",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="admissions.application",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "application review",
                "verbose_name_plural": "application reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["programme", "intended_academic_year", "status"],
                name="admissions__program_df6c1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="admissions__status_cd8e6a_idx"),
        ),
        migrations.AddConstraint(
            model_name="applicationreview",
            constraint=models.UniqueConstraint(
                fields=("application", "reviewer"), name="one_review_per_reviewer"
            ),
        ),
    ]
