# Generated by Django 5.2.17 on 2026-08-18 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0003_programme_admission_quota_rules"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("building", models.CharField(blank=True, max_length=100, verbose_name="building")),
                ("capacity", models.PositiveIntegerField(default=0, verbose_name="capacity")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExamTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("exam_date", models.DateField(verbose_name="exam date")),
                ("start_time", models.TimeField(verbose_name="starts")),
                ("end_time", models.TimeField(verbose_name="ends")),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_timetable_entries",
                        to="curriculum.course",
                    ),
                ),
                (
                    "invigilators",
                    models.ManyToManyField(
                        blank=True, related_name="invigilating_exams", to="registry.staffprofile"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_timetable_entries",
                        to="academics.semester",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_timetable_entries",
                        to="timetabling.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam timetable entry",
                "verbose_name_plural": "exam timetable entries",
                "ordering": ["exam_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["semester", "exam_date"], name="timetabling_semeste_580f17_idx"
                    ),
                    models.Index(
                        fields=["room", "exam_date"], name="timetabling_room_id_fe2d9c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "semester"),
                        name="one_exam_sitting_per_course_per_semester",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="day of week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="starts")),
                ("end_time", models.TimeField(verbose_name="ends")),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="curriculum.course",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="registry.staffprofile",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="timetabling.room",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "timetable entry",
                "verbose_name_plural": "timetable entries",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["semester", "day_of_week"], name="timetabling_semeste_fc89f4_idx"
                    ),
                    models.Index(
                        fields=["room", "semester", "day_of_week"],
                        name="timetabling_room_id_3612eb_idx",
                    ),
                    models.Index(
                        fields=["lecturer", "semester", "day_of_week"],
                        name="timetabling_lecture_6a326c_idx",
                    ),
                ],
            },
        ),
    ]
