# Generated by Django 5.2.17 on 2026-08-18 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("curriculum", "0003_programme_admission_quota_rules"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                        ],
                        default="registered",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_repeat",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically: the student has registered for this course before (FR-ENR-05).",
                        verbose_name="repeat/carry-over",
                    ),
                ),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                ("drop_reason", models.TextField(blank=True)),
                ("override_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="curriculum.course",
                    ),
                ),
                (
                    "hold_override_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when a registrar registered this student despite a blocking hold.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_registrations",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_registrations",
                        to="registry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "course registration",
                "verbose_name_plural": "course registrations",
                "ordering": ["-created_at"],
                "permissions": [
                    ("override_hold", "Can register a student despite a blocking hold"),
                    ("record_completion", "Can record a course registration as completed"),
                ],
                "indexes": [
                    models.Index(
                        fields=["course", "semester", "status"],
                        name="enrollment__course__dc8623_idx",
                    ),
                    models.Index(
                        fields=["student", "status"], name="enrollment__student_09ad0d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "course", "semester"),
                        name="one_registration_per_course_per_semester",
                    )
                ],
            },
        ),
    ]
